<?php // BigMap 2 Python export. Written by Ilya Zverev, licensed WTFPL.
header('Content-type: application/x-python');
header('Content-disposition: attachment; filename="bigmap.py"');

$l = '';
foreach( $layers as $layer ) {
	if( strlen($l) )
		$l .= ', ';
	$l .= '"'.str_replace('"', "\"", $layer).'"';
}
?>
#!/usr/bin/env python
# Generated by BigMap 2. Permalink: <?=$permalink ?>


import io, urllib2, datetime, time, re, random
from PIL import Image
# ^^^^^^ install "python-pillow" package | pip install Pillow | easy_install Pillow

(zoom, xmin, ymin, xmax, ymax) = (<?=$zoom ?>, <?=$xmin ?>, <?=$ymin ?>, <?=$xmax ?>, <?=$ymax ?>)
layers = [<?=$l ?>]
xsize = xmax - xmin + 1
ysize = ymax - ymin + 1

resultImage = Image.new("RGBA", (xsize * 256, ysize * 256), (0,0,0,0))
counter = 0
for x in range(xmin, xmax+1):
	for y in range(ymin, ymax+1):
		for layer in layers:
			url = layer.replace("!x", str(x)).replace("!y", str(y)).replace("!z", str(zoom))
			match = re.search("{([a-z0-9]+)}", url)
			if match:
				url = url.replace(match.group(0), random.choice(match.group(1)))
			print url, "... ";
			try:
				tile = urllib2.urlopen(url).read()
			except Exception, e:
				print "Error", e
				continue;
			image = Image.open(io.BytesIO(tile))
			resultImage.paste(image, ((x-xmin)*256, (y-ymin)*256), image.convert("RGBA"))
			counter += 1
			if counter == 10:
				time.sleep(2);
				counter = 0

now = datetime.datetime.now()
outputFileName = "map%02d-%02d%02d%02d-%02d%02d.png" % (zoom, now.year % 100, now.month, now.day, now.hour, now.minute)
resultImage.save(outputFileName)
